words:
- anus
- ass
- arse
- bastard
- bitch
- blowjob
- bollocks
- bollox
- boner
- chode
- clit
- cock
- cum
- cunt
- dick
- dildo
- douche
- fag
- faggot
- handjob
- jerkoff
- jizz
- kunt
- faggit
- fagget
- negro
- nigger
- ballsack
- nutsack
- pussy
- pussies
- penis
- piss
- scrote
- scrotum
- shit
- skank
- slut
- splooje
- splooge
- testicle
- tit
- boob
- twat
- vag
- vagina
- wank
- whore
- blow job
- hand job
- fuck
players:
- TechBug2012
pardoned:
- glass
- associate
- compass